bloggy/bloggy/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(
        regex=r'^admin/',
        view=admin.site.urls
    ),
    url(
        regex=r'^post/',
        view=include('post.urls', namespace='post')
    ),
    url(
        regex=r'^',
        view=include('user.urls', namespace='user')
    ),
]

bloggy/post/urls.py
from django.conf.urls import url

from .views import PostListView, PostDetailView, PostDeleteView, PostCreateView, PostCreateView
from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=PostListView.as_view(),
        name='index'
    ),
    url(
        regex=r'(?P<id>\d+)/edit/$',
        view=PostCreateView.as_view(),
        name='edit'
     ),
    url(
        regex=r'(?P<id>\d+)/delete/$',
        view=PostDeleteView.as_view(),
        name='delete'
    ),
    url(
        regex=r'add/$',
        view=PostCreateView.as_view(),
        name='add'
    ),
    url(
        regex=r'(?P<id>\d+)/$',
        view=PostDetailView.as_view(),
        name='info'
    ),
]

bloggy/user/urls.py
from django.conf.urls import url

from .views import LoginView, logout_view

urlpatterns = [
    url(
        regex=r'login/$',
        view=LoginView.as_view(),
        name='login'
    ),
    url(
        regex=r'logout/$',
        view=logout_view,
        name='logout'
    )
]

bloggy/post/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=225)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    # This can be used in reverse()
    def get_absolute_url(self):
        return reverse('post:info', kwargs={'id':self.id})

bloggy/user/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager

# Create your models here.

class CustomUserManager(BaseUserManager):

    def _create_user(self, username, email, password, is_superuser, is_staff, **extra_fields):
        """
        Creates and saves a User with the given username,  email and password.
        """
        username = username or email
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, username=None,  **extra_fields):
        return self._create_user(username, email, password, is_staff=False ,is_superuser=False, **extra_fields)

    def create_superuser(self, email, password, username=None, **extra_fields):
        return self._create_user(username, email, password, is_staff=True, is_superuser=True, **extra_fields)


class CustomUser(AbstractBaseUser):
    username = models.CharField(unique=True, max_length=255, blank=True)
    email = models.EmailField(unique=True, max_length=225)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

bloggy/post/forms.py
from django.forms import ModelForm

from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

bloggy/user/forms.py
from django import forms
from django.forms.widgets import PasswordInput


class LoginForm(forms.Form):
    username = forms.CharField(label='Username/Email')
    password = forms.CharField(widget=PasswordInput, label='Password')

    def get_username(self):
        username = cleaned_data['userame']
        return username

    def get_password(self):
        password = cleaned_data['password']
        return password

bloggy/post/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http import Http404
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, redirect
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView

from .models import Post
from .forms import PostForm


class PostListView(ListView):
    template_name = 'post/index.html'
    model = Post
    context_object_name = 'posts'
    ordering = '-created'
    paginate_by = 2


class PostUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'post/add.html'
    form_class = PostForm
    model = Post
    pk_url_kwarg = 'id'


class PostDetailView(DetailView):
    template_name = 'post/info.html'
    model = Post
    queryset = None
    context_object_name = 'post'
    pk_url_kwarg = 'id'


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    pk_url_kwarg = 'id'
    success_url = reverse_lazy('post:index')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class PostCreateView(LoginRequiredMixin, CreateView):
    template_name = 'post/add.html'
    form_class = PostForm

bloggy/user/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.views.generic import FormView
from django.contrib.auth import login, logout

from .forms import LoginForm


class LoginView(FormView):
    template_name = 'user/login.html'
    form_class = LoginForm

    def form_is_valid(self, form):
        username = form.get_username()
        password = form.get_password()

        try:
            user = authenticate(username, password)
        except DoesNotExist:
            context = {'error': u'Invalid user/password',
                   'form': self.get_form()}
            return self.render_to_response(context)
        login(self.request, user)
        return super(LoginView, self).form_is_valid(form)

    def get_success_url(self):
        return reverse('post:index')



def logout_view(request):
    logout(request)
    return redirect(reverse('post:index'))

bloggy/templates/__base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bloggy</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
    {% include '_navigation.html' %}

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
        {% endfor %}
    {% endif %}

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

bloggy/templates/_navigation.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'post:index' %}">Bloggy</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
          {{user}}
        {% if user %}
            <a class="navbar-brand" href="{% url 'post:index' %}">Hi, {{ user.email }}</a>
            <li><a href="{% url 'user:logout' %}">Logout</a></li>
        {% else %}
            <li><a href="{% url 'user:login' %}">Login</a></li>
        {% endif %}

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

bloggy/templates/post/add.html
{% extends "__base.html" %}

{% block content %}
<div class="row">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" name="submit" type="submit">Submit</button>
    </form>
</div>

{% endblock %}

bloggy/templates/post/index.html
{% extends "__base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-8">

            {% for post in posts %}
                <h2>
                    <a href="#">{{ post.title }}</a>
                </h2>

                <p>
                    <span class="glyphicon glyphicon-time"></span> Posted on {{ post.created }}
                </p>
                <hr>

                <img class="img-responsive" src="http://placehold.it/900x300" alt="">
                <hr>

                <p>{{ post.content }}</p>
                <a class="btn btn-primary" href="{{ post.get_absolute_url }}">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>
                <hr>
            {% endfor %}

            {% if is_paginated %}
            <div class="pagination">
                <span class="step-links">
                    <nav>
                        <ul class="pager">
                    {% if page_obj.has_previous %}
                        <li><a href="?page={{ page_obj.previous_page_number }}">previous</a></li>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <li><a href="?page={{ page_obj.next_page_number }}">next</a></li>
                    {% endif %}
                        </ul>
                    </nav>
                </span>
            </div>
            {% endif %}
        </div>
    </div>

{% endblock %}

bloggy/templates/post/info.html
{% extends '__base.html'%}
{% block content%}
    <div class="col-md-8">
            <h2>
                <a href="#">{{ post.title }}</a>
            </h2>

            <p>
                <span class="glyphicon glyphicon-time"></span> Posted on {{ post.created }}
            </p>
            <hr>

            <img class="img-responsive" src="http://placehold.it/900x300" alt="">
            <hr>
            <p>{{ post.content }}</p>

            <a class="btn btn-primary" href="{% url "post:edit" post.id %}">Edit</a>
            <a class="btn btn-danger" href="{% url "post:delete" post.id %}">Delete</a>
    </div>
{% endblock %}

bloggy/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <form method='POST'>
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" name="submit">Submit</button>
    </form>
</body>
</html>